# -*- coding: utf-8 -*-
"""Web Developer test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMrqh4voEjaoyrkKgyU3voIOB2ZSa8LV
"""

# package for generating the random values for dice rolls
import random

#creating the dynamic array to store all the dice rolls values
def initilize_dynamically_2d_array(row, column):

  dice_board = [ [0 for x in range(column)] for y in range(row) ]

  return dice_board

def dice_roll(board):
  
  for x in board: 
    number_of_dice = len(x)
    for i in range(0,number_of_dice):
      if x[i]=='*':
        pass
      else:
        x[i]= random.randint(1,6)
  return board

def evaluation(board, point):

    # 6 count and added number in point
  for x in range(0,len(board)):
    while( 6 in board[x]):
      point[x]+=1
      board[x].remove(6)

  temp_list = []
  # 1 found and remove and tracked how many 1s needed to add by temp_list
  for x in range(len(board)):
    count =0 
    while  1 in board[x]: 
      count+=1
      board[x].remove(1)
    temp_list.append(count) 
  print(temp_list) 

  # 1 gited
  for x in range(0, len(temp_list)-1) :
    if temp_list[x]>0:
      for i in range(temp_list[x]):
        if board[x+1]:
          board[x+1].append(1)
  
  for i in range( temp_list[-1]):
    board[0].append(1)

  return board, point
  
def star_remove(board):

    for x in board: 
      while( "*" in x ):
        x.remove('*')
    return board;

def check_end(board):
  count=0
  for x in range(len(board)):
    if board[x]:
      pass
    else:
      count+=1
  return count
  
def max(point):
  max =0 
  max_index = -1

  for i in range(len(point)):
    if point[i]>= max: 
      max = point[i]
      max_index = i
  return max_index+1  

def main():
  # taking the input values
  n = int(input( "Input N: "))
  m = int(input("Inpur M: "))

  point = [0 for x in range(n) ]

  #print(point)

  board = initilize_dynamically_2d_array(n,m)

  #print(board)
  
  i=1
  while(i<=100):
    #ending condition
    if(check_end(board)==2):
      print('************')
      print('Game Ends and Winner is player No:{}'.format(max(point)))
      print('************')
      break
    number_of_player = len(board)
  
    print("Turn {} roll the dice:".format(i))
    board = dice_roll(board)
    for x in range(1,len(point)+1): 
      print('Player #{} ({}):{}'.format(x, point[x-1], board[x-1]))
    
    print('After evaluation:')
    board,point = evaluation(board,point)
    for x in range(1,len(point)+1):
      print('Player #{} ({}):{}'.format(x, point[x-1], board[x-1]))

    #board = star_remove(board)
    #print(board)
    
    
    i+=1

    

main()